# Generated by Django 5.1.5 on 2025-06-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("especialidades", "0003_especialidad_empresa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="especialidad",
            name="empresa",
        ),
    ]
