# Generated by Django 5.1.5 on 2025-05-01 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0005_historialclinico"),
        ("procedimientos", "0003_procedimiento_tiempo_estimado_procedimiento_valor"),
        ("tratamientos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tratamiento",
            options={"ordering": ["-fecha_creacion"]},
        ),
        migrations.RenameField(
            model_name="tratamiento",
            old_name="fecha_registro",
            new_name="fecha_creacion",
        ),
        migrations.RenameField(
            model_name="tratamiento",
            old_name="notas",
            new_name="observaciones",
        ),
        migrations.RemoveField(
            model_name="tratamiento",
            name="procedimientos",
        ),
        migrations.AddField(
            model_name="tratamiento",
            name="pagado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tratamiento",
            name="procedimiento",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="procedimientos.procedimiento",
            ),
        ),
        migrations.AlterField(
            model_name="tratamiento",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("EN_PROGRESO", "En Progreso"),
                    ("COMPLETADO", "Completado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tratamiento",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tratamientos",
                to="pacientes.paciente",
            ),
        ),
        migrations.AlterField(
            model_name="tratamiento",
            name="profesional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tratamientos_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
