# Generated by Django 5.1.5 on 2025-05-01 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedimientos", "0003_procedimiento_tiempo_estimado_procedimiento_valor"),
        ("tratamientos", "0002_alter_tratamiento_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detalletratamiento",
            options={},
        ),
        migrations.RemoveField(
            model_name="detalletratamiento",
            name="precio_unitario",
        ),
        migrations.RemoveField(
            model_name="tratamiento",
            name="procedimiento",
        ),
        migrations.AlterField(
            model_name="detalletratamiento",
            name="procedimiento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="procedimientos.procedimiento",
            ),
        ),
        migrations.AlterField(
            model_name="detalletratamiento",
            name="tratamiento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="tratamientos.tratamiento",
            ),
        ),
    ]
