# Generated by Django 5.1.5 on 2025-05-01 03:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tratamientos", "0003_alter_detalletratamiento_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detalletratamiento",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Detalle de Tratamiento",
                "verbose_name_plural": "Detalles de Tratamiento",
            },
        ),
        migrations.AlterModelOptions(
            name="tratamiento",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Tratamiento",
                "verbose_name_plural": "Tratamientos",
            },
        ),
        migrations.RemoveField(
            model_name="detalletratamiento",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="tratamiento",
            name="costo_total",
        ),
        migrations.RemoveField(
            model_name="tratamiento",
            name="pagado",
        ),
        migrations.AddField(
            model_name="detalletratamiento",
            name="fecha_actualizacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="detalletratamiento",
            name="fecha_creacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="detalletratamiento",
            name="profesional",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_tratamiento",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tratamiento",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tratamientos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tratamiento",
            name="profesional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tratamientos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
