# Generated by Django 5.1.5 on 2025-05-02 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tratamientos", "0006_tratamiento_costo_total_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tratamiento",
            name="profesional",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tratamientos_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
