# Generated by Django 4.2.20 on 2025-05-02 02:53

from django.db import migrations
from django.contrib.auth import get_user_model
from django.db.models import Q


def forward_func(apps, schema_editor):
    DetalleTratamiento = apps.get_model('tratamientos', 'DetalleTratamiento')
    User = get_user_model()
    
    # Obtener el primer profesional disponible
    default_profesional = User.objects.filter(groups__name='Profesionales').first()
    
    if default_profesional:
        # Actualizar todos los registros que no tienen profesional asignado
        DetalleTratamiento.objects.filter(Q(profesional__isnull=True)).update(profesional=default_profesional)


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0007_alter_tratamiento_profesional'),
    ]

    operations = [
        migrations.RunPython(forward_func),
    ]
