# Generated by Django 5.1.5 on 2025-06-19 16:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0004_alter_empresa_options_remove_empresa_nombre_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empresa",
            options={"verbose_name": "Empresa", "verbose_name_plural": "Empresas"},
        ),
        migrations.RenameField(
            model_name="empresa",
            old_name="activo",
            new_name="activa",
        ),
        migrations.RenameField(
            model_name="empresa",
            old_name="fecha_creacion",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="empresa",
            old_name="fecha_actualizacion",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="usuarioempresa",
            old_name="fecha_creacion",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="usuarioempresa",
            old_name="fecha_actualizacion",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="fecha_fin_licencia",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="fecha_inicio_licencia",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="representante_legal",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="ruc",
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="web",
        ),
        migrations.RemoveField(
            model_name="usuarioempresa",
            name="es_administrador",
        ),
        migrations.AddField(
            model_name="empresa",
            name="rut",
            field=models.CharField(
                default="TEMP-RUT-00000000", max_length=20, unique=True
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="sitio_web",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuarioempresa",
            name="fecha_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuarioempresa",
            name="fecha_inicio",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="usuarioempresa",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrador"),
                    ("admin_empresa", "Administrador Empresa"),
                    ("admin_sucursal", "Administrador Sucursal"),
                    ("profesional", "Profesional"),
                    ("recepcion", "Recepción"),
                    ("auxiliar", "Auxiliar"),
                ],
                default="profesional",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nombre_fantasia",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="razon_social",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("horario_apertura", models.TimeField(blank=True, null=True)),
                ("horario_cierre", models.TimeField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si es la sucursal principal de la empresa",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucursales",
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
                "unique_together": {("empresa", "nombre")},
            },
        ),
        migrations.AddField(
            model_name="usuarioempresa",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresa.sucursal",
            ),
        ),
        migrations.CreateModel(
            name="PermisoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        help_text="Nombre del módulo (ej: pacientes, citas, etc.)",
                        max_length=50,
                    ),
                ),
                ("puede_ver", models.BooleanField(default=True)),
                ("puede_crear", models.BooleanField(default=False)),
                ("puede_editar", models.BooleanField(default=False)),
                ("puede_eliminar", models.BooleanField(default=False)),
                ("puede_exportar", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usuario_empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permisos",
                        to="empresa.usuarioempresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso Usuario",
                "verbose_name_plural": "Permisos Usuario",
                "unique_together": {("usuario_empresa", "modulo")},
            },
        ),
    ]
