# Generated by Django 5.1.5 on 2025-04-30 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_activo'),
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('examen', 'Examen'), ('tratamiento', 'Tratamiento'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='historiales/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_clinicos', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesionales.profesional')),
            ],
            options={
                'verbose_name': 'Historial Clínico',
                'verbose_name_plural': 'Historiales Clínicos',
                'ordering': ['-fecha'],
            },
        ),
    ]
