# Generated by Django 5.1.5 on 2025-04-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_especialidad_alter_profesional_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='especialidades',
        ),
        migrations.AddField(
            model_name='profesional',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to='profesionales.especialidad'),
        ),
    ]
