# Generated by Django 5.1.5 on 2025-04-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0002_alter_especialidad_options_alter_especialidad_estado'),
        ('profesionales', '0003_remove_profesional_especialidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to='especialidades.especialidad'),
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
