# Generated by Django 5.1.5 on 2025-09-12 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profesionales", "0009_profesional_compartir_entre_sucursales_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesional",
            name="porcentaje_utilidad",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Porcentaje de utilidad que recibe el profesional por procedimientos realizados (0.00 - 100.00)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.0, message="El porcentaje debe ser mayor o igual a 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        100.0, message="El porcentaje debe ser menor o igual a 100"
                    ),
                ],
                verbose_name="Porcentaje de Utilidad",
            ),
        ),
    ]
