# Generated by Django 5.1.5 on 2025-09-12 23:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cierres_caja",
            "0003_remove_cierrecaja_pagos_alter_cierrecaja_diferencia_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetiroCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.IntegerField(verbose_name="Monto del Retiro")),
                (
                    "concepto",
                    models.CharField(
                        help_text="Descripción del gasto o compra especial",
                        max_length=200,
                        verbose_name="Concepto del Retiro",
                    ),
                ),
                (
                    "fecha_retiro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha y Hora del Retiro",
                    ),
                ),
                (
                    "comprobante",
                    models.CharField(
                        blank=True,
                        help_text="Número de factura, boleta o comprobante del gasto",
                        max_length=100,
                        verbose_name="Número de Comprobante",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones Adicionales"
                    ),
                ),
                (
                    "cierre_caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retiros",
                        to="cierres_caja.cierrecaja",
                        verbose_name="Cierre de Caja",
                    ),
                ),
                (
                    "usuario_retiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retiros_caja",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que Retira",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retiro de Caja",
                "verbose_name_plural": "Retiros de Caja",
                "ordering": ["-fecha_retiro"],
            },
        ),
    ]
