# Generated by Django 5.1.5 on 2025-04-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_ciudad_paciente_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='documento',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
