# Generated by Django 4.2.20 on 2025-06-15 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0003_preferenciausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciausuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
