# Generated by Django 4.2.20 on 2025-05-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0016_clean_invalid_profesionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
