# Generated by Django 5.1.5 on 2025-09-11 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profesionales", "0009_profesional_compartir_entre_sucursales_and_more"),
        ("tratamientos", "0018_alter_detalletratamiento_procedimiento_pago"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SesionTratamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_sesion",
                    models.PositiveIntegerField(
                        help_text="Número de sesión dentro del tratamiento"
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateTimeField(
                        help_text="Fecha y hora programada para la sesión"
                    ),
                ),
                (
                    "fecha_realizada",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se realizó la sesión",
                        null=True,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADA", "Programada"),
                            ("REALIZADA", "Realizada"),
                            ("CANCELADA", "Cancelada"),
                            ("NO_ASISTIO", "No Asistió"),
                        ],
                        default="PROGRAMADA",
                        max_length=20,
                    ),
                ),
                (
                    "costo_sesion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Costo específico de esta sesión",
                        max_digits=10,
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, help_text="Observaciones de la sesión"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profesional",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sesiones_atendidas",
                        to="profesionales.profesional",
                    ),
                ),
                (
                    "tratamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones",
                        to="tratamientos.tratamiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Tratamiento",
                "verbose_name_plural": "Sesiones de Tratamientos",
                "ordering": ["tratamiento", "numero_sesion"],
                "unique_together": {("tratamiento", "numero_sesion")},
            },
        ),
    ]
