# Generated by Django 5.1.5 on 2025-04-24 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('procedimientos', '0001_initial'),
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedimientos.procedimiento')),
            ],
            options={
                'verbose_name': 'Detalle de Tratamiento',
                'verbose_name_plural': 'Detalles de Tratamientos',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('procedimientos', models.ManyToManyField(through='tratamientos.DetalleTratamiento', to='procedimientos.procedimiento')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profesionales.profesional')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='detalletratamiento',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamientos.tratamiento'),
        ),
    ]
