# Generated by Django 5.1.5 on 2025-05-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tratamientos", "0003_actualizar_campos"),
        ("tratamientos", "0004_alter_detalletratamiento_options_and_more"),
    ]

    operations = []
