# Generated by Django 5.1.5 on 2025-05-01 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tratamientos", "0005_merge_20250501_0130"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tratamiento",
            name="costo_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="detalletratamiento",
            name="profesional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_tratamiento",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
