# Generated by Django 4.2.20 on 2025-05-02 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tratamientos', '0008_auto_20250501_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletratamiento',
            name='profesional',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Profesionales'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_tratamiento', to=settings.AUTH_USER_MODEL),
        ),
    ]
