# Generated by Django 4.2.20 on 2025-05-02 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0005_especialidad'),
        ('tratamientos', '0009_alter_detalletratamiento_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletratamiento',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_tratamiento', to='profesionales.profesional'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos_asignados', to='profesionales.profesional'),
        ),
    ]
