# Generated by Django 5.1.5 on 2025-09-11 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagos_tratamientos", "0003_pagosesion"),
        ("tratamientos", "0019_sesiontratamiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagosesion",
            name="sesion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos_sesion",
                to="tratamientos.sesiontratamiento",
            ),
        ),
    ]
