# Generated by Django 5.1.5 on 2025-05-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0002_rename_fecha_registro_procedimiento_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='tiempo_estimado',
            field=models.IntegerField(default=30, help_text='Tiempo estimado en minutos'),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
