# Generated by Django 4.2.20 on 2025-05-03 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0002_alter_especialidad_options_alter_especialidad_estado'),
        ('procedimientos', '0003_procedimiento_tiempo_estimado_procedimiento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedimientos', to='especialidades.especialidad'),
        ),
    ]
