# Generated by Django 4.2.20 on 2025-05-18 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracion', '0002_alter_configuracionempresa_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('Poppins', 'Poppins'), ('Inter', 'Inter'), ('Outfit', 'Outfit'), ('Plus Jakarta Sans', 'Plus Jakarta Sans'), ('DM Sans', 'DM Sans')], default='Plus Jakarta Sans', max_length=50, verbose_name='Fuente del Sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Usuario',
                'verbose_name_plural': 'Preferencias de Usuarios',
            },
        ),
    ]
