# Generated by Django 5.1.5 on 2025-09-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cierres_caja", "0002_alter_cierrecaja_usuario_apertura_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cierrecaja",
            name="pagos",
        ),
        migrations.AlterField(
            model_name="cierrecaja",
            name="diferencia",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cierrecaja",
            name="monto_final",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cierrecaja",
            name="monto_inicial",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cierrecaja",
            name="total_efectivo",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cierrecaja",
            name="total_tarjeta",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cierrecaja",
            name="total_transferencia",
            field=models.IntegerField(default=0),
        ),
    ]
