# Generated by Django 4.2.20 on 2025-06-15 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cierres_caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrecaja',
            name='usuario_apertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_apertura', to=settings.AUTH_USER_MODEL, verbose_name='usuario de apertura'),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='usuario_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_cierre', to=settings.AUTH_USER_MODEL, verbose_name='usuario de cierre'),
        ),
    ]
