# Generated by Django 4.2.20 on 2025-05-03 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos_tratamientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_apertura', models.TimeField(auto_now_add=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('pagos', models.ManyToManyField(related_name='cierre_caja', to='pagos_tratamientos.pagotratamiento')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_apertura', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_cierre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha', '-hora_apertura'],
            },
        ),
    ]
