# Generated by Django 5.1.5 on 2025-09-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab_dental", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seguimientotrabajo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente de envío"),
                    ("ENVIADO", "Enviado al laboratorio"),
                    ("EN_PROCESO", "En proceso"),
                    ("LISTO", "Listo para recoger"),
                    ("RECIBIDO", "Recibido en clínica"),
                    ("DEVUELTO", "Devuelto al laboratorio"),
                    ("ENTREGADO", "Entregado al paciente"),
                    ("CANCELADO", "Cancelado"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trabajolaboratorio",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente de envío"),
                    ("ENVIADO", "Enviado al laboratorio"),
                    ("EN_PROCESO", "En proceso"),
                    ("LISTO", "Listo para recoger"),
                    ("RECIBIDO", "Recibido en clínica"),
                    ("DEVUELTO", "Devuelto al laboratorio"),
                    ("ENTREGADO", "Entregado al paciente"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
