# Generated by Django 5.1.5 on 2025-05-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimientos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimiento',
            old_name='fecha_registro',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='procedimiento',
            old_name='activo',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='procedimiento',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='precio',
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
