# Generated by Django 5.1.5 on 2025-04-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
