# Generated by Django 4.2.20 on 2025-05-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Logo')),
                ('horario_atencion', models.TextField(blank=True, verbose_name='Horario de Atención')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('terminos_condiciones', models.TextField(blank=True, verbose_name='Términos y Condiciones')),
                ('politica_privacidad', models.TextField(blank=True, verbose_name='Política de Privacidad')),
                ('redes_sociales', models.JSONField(blank=True, default=dict, verbose_name='Redes Sociales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
    ]
