# Generated by Django 4.2.20 on 2025-05-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionempresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Sube una imagen en formato PNG o JPG (tamaño recomendado: 200x200 píxeles)', null=True, upload_to='logos/', verbose_name='Logo de la empresa'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='redes_sociales',
            field=models.JSONField(blank=True, default=dict, help_text='Ingresa las URLs de tus redes sociales', null=True, verbose_name='Redes Sociales'),
        ),
    ]
