# Generated by Django 4.2.20 on 2025-06-15 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUT')),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('razon_social', models.CharField(max_length=200)),
                ('representante_legal', models.CharField(max_length=200)),
                ('fecha_inicio_licencia', models.DateField()),
                ('fecha_fin_licencia', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_administrador', models.BooleanField(default=False, verbose_name='es administrador')),
                ('fecha_union', models.DateTimeField(auto_now_add=True, verbose_name='fecha de unión')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_empresa', to='empresa.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Usuario de Empresa',
                'verbose_name_plural': 'Usuarios de Empresas',
                'db_table': 'empresa_usuarios',
            },
        ),
    ]
