# Generated by Django 4.2.20 on 2025-06-15 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioempresa',
            options={'verbose_name': 'Usuario Empresa', 'verbose_name_plural': 'Usuarios Empresa'},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='fecha_registro',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='usuarioempresa',
            name='fecha_union',
        ),
        migrations.AddField(
            model_name='usuarioempresa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarioempresa',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuarioempresa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='representante_legal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarioempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='usuarioempresa',
            name='es_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarioempresa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='usuarioempresa',
            table=None,
        ),
    ]
