# Generated by Django 5.1.5 on 2025-06-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0003_alter_usuarioempresa_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empresa",
            options={
                "ordering": ["nombre_fantasia"],
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.RemoveField(
            model_name="empresa",
            name="nombre",
        ),
        migrations.AddField(
            model_name="empresa",
            name="nombre_fantasia",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nombre de Fantasía"
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="razon_social",
            field=models.CharField(max_length=100, verbose_name="Razón Social"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="ruc",
            field=models.CharField(max_length=20, unique=True, verbose_name="RUT"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="web",
            field=models.URLField(blank=True, null=True, verbose_name="Sitio Web"),
        ),
    ]
