# Generated by Django 4.2.20 on 2025-05-18 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesionales', '0005_especialidad'),
        ('pacientes', '0006_paciente_prevision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TrabajoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajo', models.CharField(choices=[('CORONA', 'Corona'), ('PUENTE', 'Puente'), ('PROTESIS', 'Prótesis'), ('IMPLANTE', 'Implante'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADO', 'Enviado al laboratorio'), ('EN_PROCESO', 'En proceso'), ('LISTO', 'Listo para recoger'), ('RECIBIDO', 'Recibido en clínica'), ('ENTREGADO', 'Entregado al paciente'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_estimada_entrega', models.DateField()),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='lab_dental.laboratorio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_laboratorio', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_laboratorio', to='profesionales.profesional')),
            ],
            options={
                'verbose_name': 'Trabajo de Laboratorio',
                'verbose_name_plural': 'Trabajos de Laboratorio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADO', 'Enviado al laboratorio'), ('EN_PROCESO', 'En proceso'), ('LISTO', 'Listo para recoger'), ('RECIBIDO', 'Recibido en clínica'), ('ENTREGADO', 'Entregado al paciente'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('notas', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='lab_dental.trabajolaboratorio')),
            ],
            options={
                'verbose_name': 'Seguimiento de Trabajo',
                'verbose_name_plural': 'Seguimientos de Trabajos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
