# Generated by Django 5.1.5 on 2025-04-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
