# Generated by Django 5.1.5 on 2025-06-17 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedimientos", "0004_procedimiento_especialidad"),
        ("tratamientos", "0017_tratamiento_pagado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalletratamiento",
            name="procedimiento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="procedimientos.procedimiento",
            ),
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TARJETA", "Tarjeta"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PAGADO", "Pagado"),
                            ("PENDIENTE", "Pendiente"),
                            ("VENCIDO", "Vencido"),
                        ],
                        default="PAGADO",
                        max_length=20,
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=100)),
                ("notas", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tratamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_realizados",
                        to="tratamientos.tratamiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-fecha"],
            },
        ),
    ]
