# Generated by Django 4.2.20 on 2025-05-02 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tratamientos', '0016_clean_invalid_profesionales'),
        ('formas_pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=10)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se realizó el pago')),
                ('comprobante', models.CharField(blank=True, help_text='Número de comprobante o referencia del pago', max_length=50)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_tratamientos_creados', to=settings.AUTH_USER_MODEL)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_tratamientos', to='formas_pago.formapago')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='tratamientos.tratamiento')),
            ],
            options={
                'verbose_name': 'Pago de Tratamiento',
                'verbose_name_plural': 'Pagos de Tratamientos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('ANULACION', 'Anulación')], max_length=20)),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('monto_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pagos_tratamientos.pagotratamiento')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Pago',
                'verbose_name_plural': 'Historial de Pagos',
                'ordering': ['-fecha_accion'],
            },
        ),
    ]
