# Generated by Django 5.1.5 on 2025-09-11 00:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formas_pago", "0001_initial"),
        ("pagos_tratamientos", "0002_pagoatencion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, help_text="Monto del pago", max_digits=10
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora en que se realizó el pago",
                    ),
                ),
                (
                    "comprobante",
                    models.CharField(
                        blank=True,
                        help_text="Número de comprobante o referencia del pago",
                        max_length=50,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("COMPLETADO", "Completado"),
                            ("ANULADO", "Anulado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Notas adicionales sobre el pago"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_sesiones_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "forma_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_sesiones",
                        to="formas_pago.formapago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de Sesión",
                "verbose_name_plural": "Pagos de Sesiones",
                "ordering": ["-fecha_pago"],
            },
        ),
    ]
