# Generated by Django 4.2.20 on 2025-05-02 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prevision', '0001_initial'),
        ('pacientes', '0005_historialclinico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='prevision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prevision.prevision', verbose_name='Previsión'),
        ),
    ]
