# Generated by Django 5.1.5 on 2025-06-17 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0004_alter_empresa_options_remove_empresa_nombre_and_more"),
        ("especialidades", "0002_alter_especialidad_options_alter_especialidad_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="especialidad",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="especialidades",
                to="empresa.empresa",
            ),
        ),
    ]
