# Generated by Django 5.1.5 on 2025-04-30 16:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='profesional',
            options={'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'], 'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
        migrations.RenameField(
            model_name='profesional',
            old_name='fecha_registro',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='user',
        ),
        migrations.AddField(
            model_name='profesional',
            name='apellido_materno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profesional',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profesional',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profesional',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='profesional',
            name='nombres',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profesional',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AddField(
            model_name='profesional',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='especialidades',
            field=models.ManyToManyField(related_name='profesionales', to='profesionales.especialidad'),
        ),
    ]
