# Generated by Django 5.1.5 on 2025-06-15 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profesionales", "0007_profesional_empresa"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Especialidad",
        ),
    ]
