# Generated by Django 5.1.5 on 2025-06-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0005_alter_empresa_options_rename_activo_empresa_activa_and_more"),
        ("profesionales", "0008_delete_especialidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesional",
            name="compartir_entre_sucursales",
            field=models.BooleanField(
                default=False,
                help_text="Permite que otras sucursales vean este profesional",
                verbose_name="Compartir con otras sucursales",
            ),
        ),
        migrations.AddField(
            model_name="profesional",
            name="empresas_compartidas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selecciona las sucursales que pueden ver este profesional",
                related_name="profesionales_compartidos",
                to="empresa.empresa",
                verbose_name="Sucursales con acceso",
            ),
        ),
    ]
