# Generated by Django 4.2.20 on 2025-06-15 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profesionales', '0005_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesional_relacionado', to=settings.AUTH_USER_MODEL, verbose_name='usuario asociado'),
        ),
    ]
